<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 4 Week 4: Chance and Probability Theory | Lab manual QuantRMA</title>
  <meta name="description" content="The lab manual for quantitative research methods and data analysis at EUC. This text was adapted from “Answering questions with data: Lab Manual” by Matthew J.C. Crump and colleagues (https://crumplab.github.io/statistics/)" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content=" 4 Week 4: Chance and Probability Theory | Lab manual QuantRMA" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="The lab manual for quantitative research methods and data analysis at EUC. This text was adapted from “Answering questions with data: Lab Manual” by Matthew J.C. Crump and colleagues (https://crumplab.github.io/statistics/)" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 4 Week 4: Chance and Probability Theory | Lab manual QuantRMA" />
  
  <meta name="twitter:description" content="The lab manual for quantitative research methods and data analysis at EUC. This text was adapted from “Answering questions with data: Lab Manual” by Matthew J.C. Crump and colleagues (https://crumplab.github.io/statistics/)" />
  

<meta name="author" content="Original authors: Matthew J. C. Crump, Anjali Krishnan, Stephen Volz, and Alla Chavarga" />
<meta name="author" content="Adapted for EUC by Thomas Hulst and Thanos Kostopoulos" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-3-correlation-and-causation.html"/>
<link rel="next" href="week-5-estimation-and-sampling-theory.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Lab manual QuantRMA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#important-notes"><i class="fa fa-check"></i>Important notes</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#attributions"><i class="fa fa-check"></i>Attributions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#cc-by-sa-4.0-license"><i class="fa fa-check"></i>CC BY-SA 4.0 license</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html"><i class="fa fa-check"></i>Getting started</a>
<ul>
<li class="chapter" data-level="0.1" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#why-r"><i class="fa fa-check"></i><b>0.1</b> Why R?</a></li>
<li class="chapter" data-level="0.2" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#downloading-and-installing-r"><i class="fa fa-check"></i><b>0.2</b> Downloading and installing R</a>
<ul>
<li class="chapter" data-level="0.2.1" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#installing-r-on-a-mac"><i class="fa fa-check"></i><b>0.2.1</b> Installing R on a Mac</a></li>
<li class="chapter" data-level="0.2.2" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#installing-r-on-a-windows-pc"><i class="fa fa-check"></i><b>0.2.2</b> Installing R on a Windows PC</a></li>
<li class="chapter" data-level="0.2.3" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#installing-r-on-a-linux-pc"><i class="fa fa-check"></i><b>0.2.3</b> Installing R on a Linux PC</a></li>
</ul></li>
<li class="chapter" data-level="0.3" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#RStudio"><i class="fa fa-check"></i><b>0.3</b> Downloading and installing RStudio</a></li>
<li class="chapter" data-level="0.4" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#understanding-rstudio"><i class="fa fa-check"></i><b>0.4</b> Understanding RStudio</a>
<ul>
<li class="chapter" data-level="0.4.1" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#consoleR"><i class="fa fa-check"></i><b>0.4.1</b> Console</a></li>
<li class="chapter" data-level="0.4.2" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#script-editor"><i class="fa fa-check"></i><b>0.4.2</b> Script Editor</a></li>
<li class="chapter" data-level="0.4.3" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#workspace-and-history"><i class="fa fa-check"></i><b>0.4.3</b> Workspace and History</a></li>
<li class="chapter" data-level="0.4.4" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#fileplot"><i class="fa fa-check"></i><b>0.4.4</b> File, Plot, Packages, Help</a></li>
<li class="chapter" data-level="0.4.5" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#install-lib"><i class="fa fa-check"></i><b>0.4.5</b> Installing libraries</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#how-to-complete-the-labs"><i class="fa fa-check"></i><b>0.5</b> How to complete the labs</a>
<ul>
<li class="chapter" data-level="0.5.1" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#r-project"><i class="fa fa-check"></i><b>0.5.1</b> R project</a></li>
<li class="chapter" data-level="0.5.2" data-path="getting-started-adapted1.html"><a href="getting-started-adapted1.html#rmarkdown"><i class="fa fa-check"></i><b>0.5.2</b> RMarkdown</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html"><i class="fa fa-check"></i><b>1</b> Week 1: Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#learning-goals"><i class="fa fa-check"></i><b>1.1</b> Learning goals</a></li>
<li class="chapter" data-level="1.2" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#how-to-use-this-lab-manual"><i class="fa fa-check"></i><b>1.2</b> How to use this lab manual</a></li>
<li class="chapter" data-level="1.3" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#rmarkdown-basics"><i class="fa fa-check"></i><b>1.3</b> RMarkdown basics</a></li>
<li class="chapter" data-level="1.4" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#research-methods-measurement"><i class="fa fa-check"></i><b>1.4</b> Research methods: measurement</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#question-1"><i class="fa fa-check"></i><b>1.4.1</b> Question 1</a></li>
<li class="chapter" data-level="1.4.2" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#question-2"><i class="fa fa-check"></i><b>1.4.2</b> Question 2</a></li>
<li class="chapter" data-level="1.4.3" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#question-3"><i class="fa fa-check"></i><b>1.4.3</b> Question 3</a></li>
<li class="chapter" data-level="1.4.4" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#question-4"><i class="fa fa-check"></i><b>1.4.4</b> Question 4</a></li>
<li class="chapter" data-level="1.4.5" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#question-5"><i class="fa fa-check"></i><b>1.4.5</b> Question 5</a></li>
<li class="chapter" data-level="1.4.6" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#question-6"><i class="fa fa-check"></i><b>1.4.6</b> Question 6</a></li>
<li class="chapter" data-level="1.4.7" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#question-7"><i class="fa fa-check"></i><b>1.4.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#basic-r"><i class="fa fa-check"></i><b>1.5</b> Basic R</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#arithmetic"><i class="fa fa-check"></i><b>1.5.1</b> Doing simple calculations with R</a></li>
<li class="chapter" data-level="1.5.2" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#usingfunctions"><i class="fa fa-check"></i><b>1.5.2</b> Using functions to do calculations</a></li>
<li class="chapter" data-level="1.5.3" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#assign"><i class="fa fa-check"></i><b>1.5.3</b> Storing a number as a variable</a></li>
<li class="chapter" data-level="1.5.4" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#usecomments"><i class="fa fa-check"></i><b>1.5.4</b> Using comments</a></li>
<li class="chapter" data-level="1.5.5" data-path="week-1-introductionweek1-introduction-1.html"><a href="week-1-introductionweek1-introduction-1.html#r-is-pretty-stupid"><i class="fa fa-check"></i><b>1.5.5</b> R is pretty stupid?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html"><i class="fa fa-check"></i><b>2</b> Week 2: Describing Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#learning-goals-1"><i class="fa fa-check"></i><b>2.1</b> Learning goals</a></li>
<li class="chapter" data-level="2.2" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#loadingdata"><i class="fa fa-check"></i><b>2.2</b> Loading data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#firstlook"><i class="fa fa-check"></i><b>2.2.1</b> First look at the data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#making-graphs"><i class="fa fa-check"></i><b>2.3</b> Making graphs</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#wranglefirst"><i class="fa fa-check"></i><b>2.3.1</b> Wrangle first</a></li>
<li class="chapter" data-level="2.3.2" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#plotcounts"><i class="fa fa-check"></i><b>2.3.2</b> Plotting <code>counts</code></a></li>
<li class="chapter" data-level="2.3.3" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#addggplot"><i class="fa fa-check"></i><b>2.3.3</b> Additional materials: <code>ggplot()</code> layers and functions</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#gaplab"><i class="fa fa-check"></i><b>2.4</b> Gapminder dataset</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#look-at-the-data"><i class="fa fa-check"></i><b>2.4.1</b> Look at the data</a></li>
<li class="chapter" data-level="2.4.2" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#life-expectancy"><i class="fa fa-check"></i><b>2.4.2</b> Life expectancy</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#using-numbers-to-describe-data"><i class="fa fa-check"></i><b>2.5</b> Using numbers to describe data</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#playing-with-numbers"><i class="fa fa-check"></i><b>2.5.1</b> Playing with numbers</a></li>
<li class="chapter" data-level="2.5.2" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#central-tendency"><i class="fa fa-check"></i><b>2.5.2</b> Central Tendency</a></li>
<li class="chapter" data-level="2.5.3" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#variation"><i class="fa fa-check"></i><b>2.5.3</b> Variation</a></li>
<li class="chapter" data-level="2.5.4" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#descbycond"><i class="fa fa-check"></i><b>2.5.4</b> Descriptives by conditions</a></li>
<li class="chapter" data-level="2.5.5" data-path="week-2-describing-data.html"><a href="week-2-describing-data.html#describing-gapminder-with-numbers"><i class="fa fa-check"></i><b>2.5.5</b> Describing Gapminder with numbers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html"><i class="fa fa-check"></i><b>3</b> Week 3: Correlation and Causation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#learning-goals-2"><i class="fa fa-check"></i><b>3.1</b> Learning goals</a></li>
<li class="chapter" data-level="3.2" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#research-methods-causality"><i class="fa fa-check"></i><b>3.2</b> Research methods: causality</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#question-1-1"><i class="fa fa-check"></i><b>3.2.1</b> Question 1</a></li>
<li class="chapter" data-level="3.2.2" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#question-2-1"><i class="fa fa-check"></i><b>3.2.2</b> Question 2</a></li>
<li class="chapter" data-level="3.2.3" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#question-3-1"><i class="fa fa-check"></i><b>3.2.3</b> Question 3</a></li>
<li class="chapter" data-level="3.2.4" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#question-4-1"><i class="fa fa-check"></i><b>3.2.4</b> Question 4</a></li>
<li class="chapter" data-level="3.2.5" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#question-5-1"><i class="fa fa-check"></i><b>3.2.5</b> Question 5</a></li>
<li class="chapter" data-level="3.2.6" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#question-6-1"><i class="fa fa-check"></i><b>3.2.6</b> Question 6</a></li>
<li class="chapter" data-level="3.2.7" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#question-7-1"><i class="fa fa-check"></i><b>3.2.7</b> Question 7</a></li>
<li class="chapter" data-level="3.2.8" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#question-8"><i class="fa fa-check"></i><b>3.2.8</b> Question 8</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#correlations-in-r"><i class="fa fa-check"></i><b>3.3</b> Correlations in R</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#corforcor"><i class="fa fa-check"></i><b>3.3.1</b> <code>cor()</code> for correlation</a></li>
<li class="chapter" data-level="3.3.2" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#correlation-exercises"><i class="fa fa-check"></i><b>3.3.2</b> Correlation exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#real-data"><i class="fa fa-check"></i><b>3.4</b> Real data</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#load-the-data"><i class="fa fa-check"></i><b>3.4.1</b> Load the data</a></li>
<li class="chapter" data-level="3.4.2" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#look-at-the-data-1"><i class="fa fa-check"></i><b>3.4.2</b> Look at the data</a></li>
<li class="chapter" data-level="3.4.3" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#exampleq1"><i class="fa fa-check"></i><b>3.4.3</b> Example question #1</a></li>
<li class="chapter" data-level="3.4.4" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#example-question-2"><i class="fa fa-check"></i><b>3.4.4</b> Example question #2</a></li>
<li class="chapter" data-level="3.4.5" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#theory-exercises"><i class="fa fa-check"></i><b>3.4.5</b> Theory exercises</a></li>
<li class="chapter" data-level="3.4.6" data-path="week-3-correlation-and-causation.html"><a href="week-3-correlation-and-causation.html#data-exercise"><i class="fa fa-check"></i><b>3.4.6</b> Data exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html"><i class="fa fa-check"></i><b>4</b> Week 4: Chance and Probability Theory</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#learning-goals-3"><i class="fa fa-check"></i><b>4.1</b> Learning goals</a></li>
<li class="chapter" data-level="4.2" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#correlation-and-random-chance"><i class="fa fa-check"></i><b>4.2</b> Correlation and random chance</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#chanceex"><i class="fa fa-check"></i><b>4.2.1</b> Chance exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#generating-data-with-sample-and-binom"><i class="fa fa-check"></i><b>4.3</b> Generating data with <code>sample()</code> and <code>binom()</code></a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#samplefunc"><i class="fa fa-check"></i><b>4.3.1</b> <code>sample()</code></a></li>
<li class="chapter" data-level="4.3.2" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#rbinom"><i class="fa fa-check"></i><b>4.3.2</b> <code>rbinom()</code></a></li>
<li class="chapter" data-level="4.3.3" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#sample-and-binom-exercises"><i class="fa fa-check"></i><b>4.3.3</b> <code>sample</code> and <code>binom()</code> exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#normal-distribution"><i class="fa fa-check"></i><b>4.4</b> Normal distribution</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#rnorm"><i class="fa fa-check"></i><b>4.4.1</b> <code>rnorm()</code></a></li>
<li class="chapter" data-level="4.4.2" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#graphing-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.2</b> Graphing the normal distribution</a></li>
<li class="chapter" data-level="4.4.3" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#pnorm"><i class="fa fa-check"></i><b>4.4.3</b> Calculating the probability of specific ranges.</a></li>
<li class="chapter" data-level="4.4.4" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#normex"><i class="fa fa-check"></i><b>4.4.4</b> <code>norm()</code> exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#z-scores"><i class="fa fa-check"></i><b>4.5</b> z-scores</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="week-4-chance-and-probability-theory.html"><a href="week-4-chance-and-probability-theory.html#z-score-exercises"><i class="fa fa-check"></i><b>4.5.1</b> z-score exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html"><i class="fa fa-check"></i><b>5</b> Week 5: Estimation and Sampling Theory</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#learning-goals-4"><i class="fa fa-check"></i><b>5.1</b> Learning goals</a></li>
<li class="chapter" data-level="5.2" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#collecting-some-data"><i class="fa fa-check"></i><b>5.2</b> Collecting some data</a></li>
<li class="chapter" data-level="5.3" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#statistical-theory-sampling-and-estimation"><i class="fa fa-check"></i><b>5.3</b> Statistical theory: sampling and estimation</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#question-1-2"><i class="fa fa-check"></i><b>5.3.1</b> Question 1</a></li>
<li class="chapter" data-level="5.3.2" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#question-2-2"><i class="fa fa-check"></i><b>5.3.2</b> Question 2</a></li>
<li class="chapter" data-level="5.3.3" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#question-3-2"><i class="fa fa-check"></i><b>5.3.3</b> Question 3</a></li>
<li class="chapter" data-level="5.3.4" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#question-4-2"><i class="fa fa-check"></i><b>5.3.4</b> Question 4</a></li>
<li class="chapter" data-level="5.3.5" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#question-5-2"><i class="fa fa-check"></i><b>5.3.5</b> Question 5</a></li>
<li class="chapter" data-level="5.3.6" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#question-6-2"><i class="fa fa-check"></i><b>5.3.6</b> Question 6</a></li>
<li class="chapter" data-level="5.3.7" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#q7rep"><i class="fa fa-check"></i><b>5.3.7</b> Question 7</a></li>
<li class="chapter" data-level="5.3.8" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#question-8-1"><i class="fa fa-check"></i><b>5.3.8</b> Question 8</a></li>
<li class="chapter" data-level="5.3.9" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#question-9"><i class="fa fa-check"></i><b>5.3.9</b> Question 9</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#stroopdata"><i class="fa fa-check"></i><b>5.4</b> Stroop data</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#stroop-data-exercises"><i class="fa fa-check"></i><b>5.4.1</b> Stroop data exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html"><i class="fa fa-check"></i><b>6</b> Week 6: Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="6.1" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#learning-goals-5"><i class="fa fa-check"></i><b>6.1</b> Learning goals</a></li>
<li class="chapter" data-level="6.2" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#statistical-theory-hypothesis-testing"><i class="fa fa-check"></i><b>6.2</b> Statistical theory: hypothesis testing</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-1-3"><i class="fa fa-check"></i><b>6.2.1</b> Question 1</a></li>
<li class="chapter" data-level="6.2.2" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-2-3"><i class="fa fa-check"></i><b>6.2.2</b> Question 2</a></li>
<li class="chapter" data-level="6.2.3" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-3-3"><i class="fa fa-check"></i><b>6.2.3</b> Question 3</a></li>
<li class="chapter" data-level="6.2.4" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-4-3"><i class="fa fa-check"></i><b>6.2.4</b> Question 4</a></li>
<li class="chapter" data-level="6.2.5" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-5-3"><i class="fa fa-check"></i><b>6.2.5</b> Question 5</a></li>
<li class="chapter" data-level="6.2.6" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-6-3"><i class="fa fa-check"></i><b>6.2.6</b> Question 6</a></li>
<li class="chapter" data-level="6.2.7" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-7-2"><i class="fa fa-check"></i><b>6.2.7</b> Question 7</a></li>
<li class="chapter" data-level="6.2.8" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-8-2"><i class="fa fa-check"></i><b>6.2.8</b> Question 8</a></li>
<li class="chapter" data-level="6.2.9" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#question-9-1"><i class="fa fa-check"></i><b>6.2.9</b> Question 9</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#ttestR"><i class="fa fa-check"></i><b>6.3</b> <span class="math inline">\(t\)</span>-tests in R</a></li>
<li class="chapter" data-level="6.4" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#stroop-data"><i class="fa fa-check"></i><b>6.4</b> Stroop data</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="week-6-hypothesis-testing.html"><a href="week-6-hypothesis-testing.html#t-test-exercises"><i class="fa fa-check"></i><b>6.4.1</b> <span class="math inline">\(t\)</span>-test exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="function-list.html"><a href="function-list.html"><i class="fa fa-check"></i><b>7</b> Function list</a>
<ul>
<li class="chapter" data-level="7.1" data-path="function-list.html"><a href="function-list.html#week-1"><i class="fa fa-check"></i><b>7.1</b> Week 1</a></li>
<li class="chapter" data-level="7.2" data-path="function-list.html"><a href="function-list.html#week-2"><i class="fa fa-check"></i><b>7.2</b> Week 2</a></li>
<li class="chapter" data-level="7.3" data-path="function-list.html"><a href="function-list.html#week-3"><i class="fa fa-check"></i><b>7.3</b> Week 3</a></li>
<li class="chapter" data-level="7.4" data-path="function-list.html"><a href="function-list.html#week-4"><i class="fa fa-check"></i><b>7.4</b> Week 4</a></li>
<li class="chapter" data-level="7.5" data-path="function-list.html"><a href="function-list.html#week-5"><i class="fa fa-check"></i><b>7.5</b> Week 5</a></li>
<li class="chapter" data-level="7.6" data-path="function-list.html"><a href="function-list.html#week-6"><i class="fa fa-check"></i><b>7.6</b> Week 6</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>8</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Lab manual QuantRMA</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-4-chance-and-probability-theory" class="section level1" number="4">
<h1><span class="header-section-number"> 4</span> Week 4: Chance and Probability Theory</h1>
<p>In the textbook we learned that we can find correlations by <strong>chance alone</strong>, even when there is no true correlation between two variables. During the first part of this lab we are going to explore this phenomenon further. We will generate some random data and then look at the correlations we calculate from random data. This will serve to develop our intuitions about inferential statistics; the focus of the remainder of this course. In the second part of the lab we are going to dive deeper in generating simulated data, which is very useful in helping us understand real data, and calculate all sorts of things about probability distributions.</p>
<p>To get started, download the <a href="https://github.com/thomashulst/quantrma_lab/raw/master/Labs/Lab04_Probability.Rmd">lab template here</a> (right click: save as) or from Canvas. Copy the lab template to your lab folder and double click the <strong>Lab project file</strong> (not the .Rmd) to open RStudio.</p>
<div id="learning-goals-3" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Learning goals</h2>
<p>During this lab you will do the following:</p>
<ol style="list-style-type: decimal">
<li>Explore correlations and random chance</li>
<li>Learn how to generate simulated data in R</li>
<li>Calculate and work with z-scores in R</li>
</ol>
</div>
<div id="correlation-and-random-chance" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Correlation and random chance</h2>
<p>We saw <a href="https://thomashulst.github.io/quantrma/chchance.html#correlation-and-random-chance">in the textbook</a>, that we can find correlations by chance alone, even when there is no true correlation between the variables. For example, suppose we randomly sampled some numbers into <code>x</code> and <code>y</code>. We know they shouldn’t be related, because we randomly sampled the numbers. However, chance alone will sometimes create correlations between <code>x</code> and <code>y</code>. You can demonstrate this to yourself by using the code below. Let’s look at 20 “experiments,” with 5 random numbers for <code>x</code> and <code>y</code> each.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="week-4-chance-and-probability-theory.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb182-2"><a href="week-4-chance-and-probability-theory.html#cb182-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb182-3"><a href="week-4-chance-and-probability-theory.html#cb182-3" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">5</span><span class="sc">*</span><span class="dv">20</span>,<span class="dv">5</span>,<span class="dv">5</span>)) <span class="co"># rnorm draws random numbers from a normal distribution</span></span>
<span id="cb182-4"><a href="week-4-chance-and-probability-theory.html#cb182-4" aria-hidden="true" tabindex="-1"></a>y<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">5</span><span class="sc">*</span><span class="dv">20</span>,<span class="dv">5</span>,<span class="dv">5</span>)) </span>
<span id="cb182-5"><a href="week-4-chance-and-probability-theory.html#cb182-5" aria-hidden="true" tabindex="-1"></a>conditions<span class="ot">&lt;-</span><span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>, <span class="at">each=</span><span class="dv">5</span>)</span>
<span id="cb182-6"><a href="week-4-chance-and-probability-theory.html#cb182-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb182-7"><a href="week-4-chance-and-probability-theory.html#cb182-7" aria-hidden="true" tabindex="-1"></a><span class="co"># put data in data.frame</span></span>
<span id="cb182-8"><a href="week-4-chance-and-probability-theory.html#cb182-8" aria-hidden="true" tabindex="-1"></a>all_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(conditions, x, y)</span>
<span id="cb182-9"><a href="week-4-chance-and-probability-theory.html#cb182-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb182-10"><a href="week-4-chance-and-probability-theory.html#cb182-10" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 20 scatterplots with best fit line</span></span>
<span id="cb182-11"><a href="week-4-chance-and-probability-theory.html#cb182-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(all_df, <span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span></span>
<span id="cb182-12"><a href="week-4-chance-and-probability-theory.html#cb182-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb182-13"><a href="week-4-chance-and-probability-theory.html#cb182-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb182-14"><a href="week-4-chance-and-probability-theory.html#cb182-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>conditions)<span class="sc">+</span></span>
<span id="cb182-15"><a href="week-4-chance-and-probability-theory.html#cb182-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-85-1.png" width="672" /></p>
<p>You can see that the slope of the blue line is not always flat. Sometimes it looks like there is a correlation, when we know in fact the data is completely random. You can keep re-doing this graph, by re-knitting your RMarkdown document, or by pressing the little green play button. This is basically you simulating 20 experiments each time you press the button. Complete the chance exercises below in your RMarkdown template.</p>
<div id="chanceex" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Chance exercises</h3>
<p>For the first two exercises, you will be sampling random numbers from a normal distribution a 1000 times. We provide some hints and example code two answer the exercises below.</p>
<ol style="list-style-type: decimal">
<li>Estimate the range (minimum and maximum) of correlations that could occur by chance between two normally distributed random variables with n = 10.</li>
<li>Estimate the range (minimum and maximum) of correlations that could occur by chance between two normally distributed random variables with n = 25.</li>
</ol>
<p>Hint: to estimate the range of correlations that chance can produce we randomly sample <code>x</code> and <code>y</code> many times (like in the first example), save the correlation between <code>x</code> and <code>y</code> each time, then look at the smallest and largest correlation. How can you do this programmatically, without having to press the ‘play’ button hundreds of times?</p>
<p>The answer is using a <code>for</code> loop. The code below shows how to repeat everything inside the for loop 5 times. The variable <code>i</code> is an index, that goes from 1 to 5. The <code>saved_value</code> variable starts out as an empty variable, and then we put a value into it (at index position i, from 1 to 5). In this code, we put the sum of the products of x and y into the <code>saved_value</code> variable. At the end of the simulation, the <code>saved_value</code> variable contains 5 numbers. The <code>min()</code> and <code>max()</code> functions are used to find the minimum and maximum values for each of the 5 simulations. Modify the following code to answer question 1 and 2.</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="week-4-chance-and-probability-theory.html#cb183-1" aria-hidden="true" tabindex="-1"></a>saved_value <span class="ot">&lt;-</span> <span class="fu">c</span>() <span class="co"># create empty variable</span></span>
<span id="cb183-2"><a href="week-4-chance-and-probability-theory.html#cb183-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) { <span class="co"># loop over code between {} 5 times</span></span>
<span id="cb183-3"><a href="week-4-chance-and-probability-theory.html#cb183-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">10</span>, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">5</span>) <span class="co"># generate normally distributed random variables</span></span>
<span id="cb183-4"><a href="week-4-chance-and-probability-theory.html#cb183-4" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">10</span>, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">5</span>)</span>
<span id="cb183-5"><a href="week-4-chance-and-probability-theory.html#cb183-5" aria-hidden="true" tabindex="-1"></a>  saved_value[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">*</span>y) <span class="co"># save the sum of the product of x*y in saved_value</span></span>
<span id="cb183-6"><a href="week-4-chance-and-probability-theory.html#cb183-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb183-7"><a href="week-4-chance-and-probability-theory.html#cb183-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-8"><a href="week-4-chance-and-probability-theory.html#cb183-8" aria-hidden="true" tabindex="-1"></a>min_value <span class="ot">&lt;-</span> <span class="fu">min</span>(saved_value)</span>
<span id="cb183-9"><a href="week-4-chance-and-probability-theory.html#cb183-9" aria-hidden="true" tabindex="-1"></a>max_value <span class="ot">&lt;-</span> <span class="fu">max</span>(saved_value)</span>
<span id="cb183-10"><a href="week-4-chance-and-probability-theory.html#cb183-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-11"><a href="week-4-chance-and-probability-theory.html#cb183-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(min_value)</span></code></pre></div>
<pre><code>## [1] -118.9097</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="week-4-chance-and-probability-theory.html#cb185-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(max_value)</span></code></pre></div>
<pre><code>## [1] 65.00331</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><p>What proportion of simulated correlations (from question 1 and 2) is smaller than -0.3 and larger than +0.3 for n = 10 and n = 25? To calculate the proportion use the smaller than (<code>&lt;</code>) and greater than (<code>&gt;</code>) operators on your vector of correlations like so: <code>mean(saved_value &lt; 0.3)</code></p></li>
<li><p>The histogram below shows the correlations produced by random chance for n = 10. The red lines are set at -0.3 and +0.3. The text indicates the proportion of correlations outside the red lines. Try to recreate the histogram below as closely as possible for n = 25.</p></li>
</ol>
<p>Remember, programming is an iterative process, you almost never get to the solution in the first go. Make liberal use of the help function in R, Google, the tidyverse website and/or the cheatsheets and ask help from your classmates / the tutor when stuck. There are multiple ways to get to the plot below.</p>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<p>After completing these exercises, continue the lab by reading Section 4.3.</p>
</div>
</div>
<div id="generating-data-with-sample-and-binom" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Generating data with <code>sample()</code> and <code>binom()</code></h2>
<p>There are many ways to make R generate numbers for you. We already used normal distribution to generate numbers for our random correlations. In this next part, we will explore additional functions and distributions to generate random numbers and look at <code>rnorm()</code> in more detail.</p>
<div id="samplefunc" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> <code>sample()</code></h3>
<p>The sample function is like an endless gumball machine. You put the gumballs inside with different properties, say As and Bs, and then you let sample endlessly take gumballs out. Check it out:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="week-4-chance-and-probability-theory.html#cb187-1" aria-hidden="true" tabindex="-1"></a>gumballs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>)</span>
<span id="cb187-2"><a href="week-4-chance-and-probability-theory.html#cb187-2" aria-hidden="true" tabindex="-1"></a>sample_of_gumballs <span class="ot">&lt;-</span><span class="fu">sample</span>(gumballs, <span class="dv">10</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb187-3"><a href="week-4-chance-and-probability-theory.html#cb187-3" aria-hidden="true" tabindex="-1"></a>sample_of_gumballs</span></code></pre></div>
<pre><code>##  [1] &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot;</code></pre>
<p>Here the sample function randomly picks A or B each time. We set it do this 10 times, so our sample has 10 things in it. We set <code>replace=TRUE</code> so that after each sample, we put the item back into the gumball machine and start again. Here’s another example with numbers:</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="week-4-chance-and-probability-theory.html#cb189-1" aria-hidden="true" tabindex="-1"></a>some_numbers <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">5</span>)</span>
<span id="cb189-2"><a href="week-4-chance-and-probability-theory.html#cb189-2" aria-hidden="true" tabindex="-1"></a>sample_of_numbers <span class="ot">&lt;-</span><span class="fu">sample</span>(some_numbers, <span class="dv">20</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb189-3"><a href="week-4-chance-and-probability-theory.html#cb189-3" aria-hidden="true" tabindex="-1"></a>sample_of_numbers</span></code></pre></div>
<pre><code>##  [1] 5 5 5 3 5 5 5 3 5 5 5 5 2 5 4 4 4 3 5 5</code></pre>
<p>Let’s do one more thing with sample. Let’s sample 1000 times from our <code>some_numbers</code> variable, and then look at the histogram:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="week-4-chance-and-probability-theory.html#cb191-1" aria-hidden="true" tabindex="-1"></a>some_numbers <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">5</span>)</span>
<span id="cb191-2"><a href="week-4-chance-and-probability-theory.html#cb191-2" aria-hidden="true" tabindex="-1"></a>sample_of_numbers <span class="ot">&lt;-</span><span class="fu">sample</span>(some_numbers, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb191-3"><a href="week-4-chance-and-probability-theory.html#cb191-3" aria-hidden="true" tabindex="-1"></a>sample_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(sample_of_numbers)</span>
<span id="cb191-4"><a href="week-4-chance-and-probability-theory.html#cb191-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb191-5"><a href="week-4-chance-and-probability-theory.html#cb191-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sample_df,<span class="fu">aes</span>(<span class="at">x=</span>sample_of_numbers)) <span class="sc">+</span> </span>
<span id="cb191-6"><a href="week-4-chance-and-probability-theory.html#cb191-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p>We are looking at lots of samples from our little gumball machine of numbers. Notice that as we put more 5s in, more 5s come out of in our big sample of 1000.</p>
</div>
<div id="rbinom" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> <code>rbinom()</code></h3>
<p>You can think of the binomial distribution as a coin flipping distribution. Or dice roll distribution. Or anything you can define a number of “successes” for. For example, when flipping a coin, we could consider flipping heads a “success.”</p>
<p>You use <code>rbinom</code> as follows: <code>rbinom(n, size, prob)</code>. <code>n</code> gives the number of flips you want to make. <code>size</code> is the number of coins you want to flip at once. <code>prob</code> is the probability that defines how often a “success” happens. Here’s how we flip one coin 10 times using <code>rbinom</code> (assuming the coin is fair):</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="week-4-chance-and-probability-theory.html#cb192-1" aria-hidden="true" tabindex="-1"></a>coin_flips <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">10</span>,<span class="dv">1</span>,.<span class="dv">5</span>)</span>
<span id="cb192-2"><a href="week-4-chance-and-probability-theory.html#cb192-2" aria-hidden="true" tabindex="-1"></a>coin_flips</span></code></pre></div>
<pre><code>##  [1] 1 0 1 0 1 1 0 1 0 0</code></pre>
<p>We get a bunch of 0s, and 1s. We can pretend 0 = tails, and 1 = heads. If you flip 10 coins, how many heads do you get? We can can do the above again, and then <code>sum(coin_flips)</code>.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="week-4-chance-and-probability-theory.html#cb194-1" aria-hidden="true" tabindex="-1"></a>coin_flips <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">10</span>,<span class="dv">1</span>,.<span class="dv">5</span>)</span>
<span id="cb194-2"><a href="week-4-chance-and-probability-theory.html#cb194-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(coin_flips)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Alright, so we get the sum of the 1s (i.e. the successes), which tells us the number of heads. But, if you keep redoing the above, you’ll get different answers each time. 5 heads will be the most frequent answer, but you will get lots of other answers too.</p>
<p>We could do this 1000 times over, saving the number of heads for each set of 10 flips. Then we could look at the distribution of those sums. That would tell us about the range of things that can happen when we flip a coin 10 times. We can do that in a <code>for</code> loop like this:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="week-4-chance-and-probability-theory.html#cb196-1" aria-hidden="true" tabindex="-1"></a>number_of_heads<span class="ot">&lt;-</span><span class="fu">length</span>(<span class="dv">1000</span>) <span class="co"># make an empty variable to save things in</span></span>
<span id="cb196-2"><a href="week-4-chance-and-probability-theory.html#cb196-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-3"><a href="week-4-chance-and-probability-theory.html#cb196-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb196-4"><a href="week-4-chance-and-probability-theory.html#cb196-4" aria-hidden="true" tabindex="-1"></a>  number_of_heads[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">rbinom</span>(<span class="dv">10</span>,<span class="dv">1</span>,.<span class="dv">5</span>))</span>
<span id="cb196-5"><a href="week-4-chance-and-probability-theory.html#cb196-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb196-6"><a href="week-4-chance-and-probability-theory.html#cb196-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-7"><a href="week-4-chance-and-probability-theory.html#cb196-7" aria-hidden="true" tabindex="-1"></a>heads_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(number_of_heads)</span>
<span id="cb196-8"><a href="week-4-chance-and-probability-theory.html#cb196-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-9"><a href="week-4-chance-and-probability-theory.html#cb196-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heads_df,<span class="fu">aes</span>(<span class="at">x=</span>number_of_heads)) <span class="sc">+</span></span>
<span id="cb196-10"><a href="week-4-chance-and-probability-theory.html#cb196-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="dv">1</span>,<span class="at">fill=</span><span class="st">&quot;white&quot;</span>,<span class="at">color=</span><span class="st">&quot;black&quot;</span>) </span></code></pre></div>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>The histogram shows us the frequency observing different numbers of heads (for 10 flips) across the 1000 simulations. 5 happens the most, but 2 happens sometimes, and so does 8. All of the possibilities seem to happen sometimes, some more than others.</p>
</div>
<div id="sample-and-binom-exercises" class="section level3" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> <code>sample</code> and <code>binom()</code> exercises</h3>
<ol style="list-style-type: decimal">
<li>Why are you unable to run the following bit of code? What could you do to fix this? Does this change the nature of your sampling procedure?</li>
</ol>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="week-4-chance-and-probability-theory.html#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>), <span class="dv">20</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li><p>Simulate the amount of sixes you expect to roll when rolling 1 dice 10,000 times. Also simulate the amount of fives <strong>and</strong> sixes you expect to roll when rolling 10 dice 10,000 times? (hint: use <code>rbinom()</code> to simulate 10,000 dice rolls and <code>sum()</code> to calculate the amount of successes)</p></li>
<li><p>What is the probability of obtaining exactly 4 heads when flipping 10 fair coins? And what is the probability to obtain <strong>at most</strong> 4 heads (so 0, 1, 2, 3, or 4 heads)? Cf. <a href="https://thomashulst.github.io/quantrma/chchance.html#working-with-the-binomial-distribution-in-r">the textbook</a> when unsure how to use the <code>binom()</code> functions.</p></li>
<li><p>What is the probability to obtain <strong>at least</strong> 4 heads (so 4, 5, 6, 7, 8, 9, or 10 heads) when flipping 10 fair coins? You can calculate this probability in two ways, either by using <code>pbinom()</code> with an additional argument, or by using your answers from question 3.</p></li>
</ol>
</div>
</div>
<div id="normal-distribution" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Normal distribution</h2>
<div id="rnorm" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> <code>rnorm()</code></h3>
<p>You can use <code>rnorm()</code> to sample numbers from a normal distribution. It’s similar to <code>rbinom()</code>, but now you are sampling from a normal distribution instead:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="week-4-chance-and-probability-theory.html#cb198-1" aria-hidden="true" tabindex="-1"></a>sample_numbers <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>,<span class="dv">0</span>,<span class="dv">1</span>) <span class="co"># sample n = 10,000 numbers with mean = 0 and sd=1</span></span>
<span id="cb198-2"><a href="week-4-chance-and-probability-theory.html#cb198-2" aria-hidden="true" tabindex="-1"></a>sample_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(sample_numbers)</span>
<span id="cb198-3"><a href="week-4-chance-and-probability-theory.html#cb198-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb198-4"><a href="week-4-chance-and-probability-theory.html#cb198-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sample_df,<span class="fu">aes</span>(<span class="at">x=</span>sample_numbers)) <span class="sc">+</span></span>
<span id="cb198-5"><a href="week-4-chance-and-probability-theory.html#cb198-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.1</span>,<span class="at">fill=</span><span class="st">&quot;white&quot;</span>,<span class="at">color=</span><span class="st">&quot;black&quot;</span>) </span></code></pre></div>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-95-1.png" width="672" /></p>
<p>There it is, a bell-shaped normal distribution with a mean of 0, and a standard deviation of 1. Just by changing the arguments of the <code>rnorm()</code> function, you can sample numbers from normal distributions with any mean or standard deviation.</p>
<p>The nice thing about R functions is that they are a bit like Legos, you can put them together and come up with different things. What if wanted to sample from a distribution that looked like a two-humped camel’s back? Just sample from <code>rnorm</code> twice like this… mix away.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="week-4-chance-and-probability-theory.html#cb199-1" aria-hidden="true" tabindex="-1"></a>sample_numbers <span class="ot">&lt;-</span> ( <span class="fu">c</span>( <span class="fu">rnorm</span>(<span class="dv">10000</span>,<span class="dv">25</span>,<span class="fl">7.5</span>), <span class="fu">rnorm</span>(<span class="dv">10000</span>,<span class="dv">50</span>,<span class="fl">7.5</span>)) )</span>
<span id="cb199-2"><a href="week-4-chance-and-probability-theory.html#cb199-2" aria-hidden="true" tabindex="-1"></a>sample_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(sample_numbers)</span>
<span id="cb199-3"><a href="week-4-chance-and-probability-theory.html#cb199-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb199-4"><a href="week-4-chance-and-probability-theory.html#cb199-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sample_df,<span class="fu">aes</span>(<span class="at">x=</span>sample_numbers)) <span class="sc">+</span></span>
<span id="cb199-5"><a href="week-4-chance-and-probability-theory.html#cb199-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="dv">1</span>,<span class="at">fill=</span><span class="st">&quot;white&quot;</span>,<span class="at">color=</span><span class="st">&quot;black&quot;</span>) </span></code></pre></div>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-96-1.png" width="672" />
You can generate as many numbers under a certain distribution as your computer can handle.</p>
</div>
<div id="graphing-the-normal-distribution" class="section level3" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Graphing the normal distribution</h3>
<p>“Wait, I thought we already graphed a normal distribution.” We sort of did. We sampled numbers and made histograms that looked like a normal distribution. But, a normal distribution is more of an abstract idea. It looks like this in the abstract:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="week-4-chance-and-probability-theory.html#cb200-1" aria-hidden="true" tabindex="-1"></a>normal_dist <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>,.<span class="dv">1</span>), <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb200-2"><a href="week-4-chance-and-probability-theory.html#cb200-2" aria-hidden="true" tabindex="-1"></a>values <span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>,.<span class="dv">1</span>)</span>
<span id="cb200-3"><a href="week-4-chance-and-probability-theory.html#cb200-3" aria-hidden="true" tabindex="-1"></a>normal_df <span class="ot">&lt;-</span><span class="fu">data.frame</span>(values,normal_dist)</span>
<span id="cb200-4"><a href="week-4-chance-and-probability-theory.html#cb200-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb200-5"><a href="week-4-chance-and-probability-theory.html#cb200-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(normal_df, <span class="fu">aes</span>(<span class="at">x=</span>values,<span class="at">y=</span>normal_dist))<span class="sc">+</span></span>
<span id="cb200-6"><a href="week-4-chance-and-probability-theory.html#cb200-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb200-7"><a href="week-4-chance-and-probability-theory.html#cb200-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<p>A really nice shaped bell-like thing. This normal distribution has a mean of 0, and standard deviation of 1. The heights of the lines tell you roughly how likely each value is. Notice, it is centered on 0 (most likely that numbers from this distribution will be near 0), and it goes down as numbers get bigger or smaller (so bigger or smaller numbers get less likely). Notice the values don’t go much beyond -4 and +4. This is because those values don’t happen very often. Theoretically any value could happen, but really big or small values have really low probabilities.</p>
</div>
<div id="pnorm" class="section level3" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> Calculating the probability of specific ranges.</h3>
<p>We can use R to tell us about the probability of getting numbers in a certain range. For example, when you think about it, it should be obvious that you have a 50% probability of getting the number 0 or lower. Half of the distribution is 0 or lower, so you have a 50% probability.</p>
<p>We can use the <code>pnorm()</code> function to confirm this:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="week-4-chance-and-probability-theory.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">0</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd=</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<p>Agreed, <code>pnorm()</code> tells us the probability of getting 0 or lower is 0.5.
Well, what is the probability of getting a 2 or greater? That’s a bit harder to judge, but obviously less than 50%. Use R like this to find out:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="week-4-chance-and-probability-theory.html#cb203-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">2</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd=</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.9772499</code></pre>
<p>That doesn’t seem quite right. R is telling us the probability is 0.977, while we know it should be smaller than 0.5. That’s because by default, <code>pnorm()</code> gives the probability “up to and including” (denoted: P[X ≤ x]). The figure below visualizes what that means:</p>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-100-1.png" width="672" />
So, to get the probability of getting a 2 or greater, we have to take <span class="math inline">\(1 - 0.9772499 = 0.0227501\)</span>:</p>
<p><img src="quantrma_lab_files/figure-html/unnamed-chunk-101-1.png" width="672" />
Or, we could use the <code>lower.tail</code> argument:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="week-4-chance-and-probability-theory.html#cb205-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">2</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd=</span> <span class="dv">1</span>,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.02275013</code></pre>
<p>So, the probability of getting a 2 or greater is .0227 (not very probable)</p>
</div>
<div id="normex" class="section level3" number="4.4.4">
<h3><span class="header-section-number">4.4.4</span> <code>norm()</code> exercises</h3>
<p>Complete the following exercises in your RMarkdown template.</p>
<p>Run the following bit of code, which samples 20 random numbers from a normal distribution, a couple of times and look at the results.</p>
<ol style="list-style-type: decimal">
<li>What do you think the function <code>set.seed()</code> does? When do you think this could be useful?</li>
</ol>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="week-4-chance-and-probability-theory.html#cb207-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb207-2"><a href="week-4-chance-and-probability-theory.html#cb207-2" aria-hidden="true" tabindex="-1"></a>some_numbers <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">25</span>) <span class="co"># 20 numbers, mean = 50, s.d. = 25</span></span>
<span id="cb207-3"><a href="week-4-chance-and-probability-theory.html#cb207-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(some_numbers)</span></code></pre></div>
<pre><code>##  [1] 35.9881088 44.2455628 88.9677079 51.7627098 53.2321934 92.8766247
##  [7] 61.5229051 18.3734691 32.8286787 38.8584507 80.6020449 58.9953457
## [13] 60.0192863 52.7670679 36.1039716 94.6728284 62.4462620  0.8345711
## [19] 67.5338975 38.1802148</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><p>Suppose the mean of a normal distribution is 25 (<span class="math inline">\(\mu = 25\)</span>) and the standard deviation is 3 (<span class="math inline">\(\sigma=3\)</span>). Calculate the probability of obtaining a value between 22 and 28 using R. (hint: <code>pnorm()</code>)</p></li>
<li><p>Based on what you know about the standard normal distribution, could you answer question 2 without calculations?</p></li>
<li><p>Use R to calculate the probability of obtaining a value <strong>higher than 29.5</strong> for the normal distribution with <span class="math inline">\(\mu = 25\)</span> and <span class="math inline">\(\sigma=3\)</span>. (hint: <code>pnorm()</code>)</p></li>
</ol>
<p>Continue the lab by reading section 4.5 of the lab manual.</p>
</div>
</div>
<div id="z-scores" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> z-scores</h2>
<p>A normal distribution with mean = 0 and the standard deviation = 1 is called the <strong>standard normal distribution</strong>. Often, we are not dealing with a normal distribution exactly like this.</p>
<p>For example, someone might say, I got a number, it’s 545. It came from a normal distribution with mean = 600, and standard deviation = 25. Does the number 545 happen a lot or not? The numbers don’t tell you right away. But if we were talking about the standard normal distribution with mean = 0 and standard deviation = 1, and I told I got a number -2.2 from that distribution, you would know directly that -2.2 doesn’t happen a lot.</p>
<p>z-scores are a way of transforming one set of numbers into the standard normal distribution. To <a href="https://thomashulst.github.io/quantrma/chchance.html#z-score">calculate z-scores</a> we take the following steps:</p>
<ol style="list-style-type: decimal">
<li>First get some numbers:</li>
</ol>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="week-4-chance-and-probability-theory.html#cb209-1" aria-hidden="true" tabindex="-1"></a>some_numbers <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">25</span>) <span class="co"># 20 numbers, mean = 50, s.d. = 25</span></span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the mean and standard deviation:</li>
</ol>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="week-4-chance-and-probability-theory.html#cb210-1" aria-hidden="true" tabindex="-1"></a>my_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(some_numbers)</span>
<span id="cb210-2"><a href="week-4-chance-and-probability-theory.html#cb210-2" aria-hidden="true" tabindex="-1"></a>my_sd <span class="ot">&lt;-</span><span class="fu">sd</span>(some_numbers)</span>
<span id="cb210-3"><a href="week-4-chance-and-probability-theory.html#cb210-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb210-4"><a href="week-4-chance-and-probability-theory.html#cb210-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(my_mean)</span></code></pre></div>
<pre><code>## [1] 48.71857</code></pre>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="week-4-chance-and-probability-theory.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(my_sd)</span></code></pre></div>
<pre><code>## [1] 20.74847</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Subtract the mean from your numbers:</li>
</ol>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="week-4-chance-and-probability-theory.html#cb214-1" aria-hidden="true" tabindex="-1"></a>differences<span class="ot">&lt;-</span>some_numbers<span class="sc">-</span>my_mean</span>
<span id="cb214-2"><a href="week-4-chance-and-probability-theory.html#cb214-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(differences)</span></code></pre></div>
<pre><code>##  [1] -25.4141636  -4.1679438 -24.3686822 -16.9408517 -14.3445527 -40.8859037
##  [7]  22.2261051   5.1157570 -27.1719944  32.6268021  11.9430346  -6.0953580
## [13]  23.6595706  23.2347662  21.8209561  18.4974354  15.1293704  -0.2663637
## [19]  -6.3676376  -8.2303460</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Divide each number by the standard deviation:</li>
</ol>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="week-4-chance-and-probability-theory.html#cb216-1" aria-hidden="true" tabindex="-1"></a>z_scores<span class="ot">&lt;-</span>differences<span class="sc">/</span>my_sd</span>
<span id="cb216-2"><a href="week-4-chance-and-probability-theory.html#cb216-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(z_scores)</span></code></pre></div>
<pre><code>##  [1] -1.22486947 -0.20087961 -1.17448110 -0.81648691 -0.69135482 -1.97055060
##  [7]  1.07121675  0.24656072 -1.30959047  1.57249219  0.57561046 -0.29377390
## [13]  1.14030452  1.11983051  1.05169005  0.89150854  0.72918016 -0.01283775
## [19] -0.30689677 -0.39667249</code></pre>
<p>Done. Now you have converted your original numbers into what we call standardized scores (or z-scores). They are standardized to have the same (assumed) properties of a normal distribution with mean = 0, and standard deviation = 1.</p>
<div id="z-score-exercises" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> z-score exercises</h3>
<p>Complete the following exercises in your RMarkdown template.</p>
<p><a href="https://github.com/thomashulst/quantrma_lab/blob/master/data/spssdata/StatsGrades.sav?raw=true">Right click and download this</a> SPSS file containing 49 students’ exam grades (let’s say it’s the final exam for a statistics class). You have likely never worked with an SPSS (.sav) file before, but luckily a library that can load SPSS files was installed when installing the tidyverse. To load this package (it is not loaded by default with <code>library(tidyverse)</code>), use <code>library(haven)</code>. Make sure the .sav is in your lab directory so you can load it into R.</p>
<p>Once you have successfully loaded the data into R:</p>
<ol style="list-style-type: decimal">
<li>Create a table containing the mean and standard deviation for this sample of scores. Also produce a histogram of the grades. How does the distribution of grades look when you plot your histogram with a binwidth of 5?</li>
<li>Transform each student’s score into a Z-score. Now, plot the frequency histogram of this Z-score distribution with a binwidth of 0.5. Compare it to the raw score distribution. How are they the same? How are they different?</li>
<li>Imagine you are a student in this class who received a 90 on this exam. However, the Professor has decided to grade on a curve, such that only the top 10% of the class receives an A. Calculate the z-score that corresponds to a raw score of 90 on this exam. Will you get an A with this grade? Why or why not?</li>
</ol>
<p>When you have completed all exercises and are happy with your progress today, please knit your document and submit it to Canvas. If you finish before the time is up, start with the required readings of Week 5, work on your assignment, or help out your fellow students.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-3-correlation-and-causation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-5-estimation-and-sampling-theory.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
